services:

  pg-primary:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    depends_on:
      - pg-sync-replica
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=pgqp_primary_user
      - POSTGRESQL_REPLICATION_PASSWORD=pgqp_primary_password
      - POSTGRESQL_DATABASE=pgqp_db
      - POSTGRESQL_USERNAME=pgqp_user
      - POSTGRESQL_PASSWORD=pgqp_password
      - POSTGRESQL_MAX_CONNECTIONS=500
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=remote_apply
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1

  pg-sync-replica:
    image: bitnami/postgresql:latest
    ports:
      - 6543:5432
    volumes:
      - ./pg-configs/sync-replica/conf:/opt/bitnami/postgresql/conf
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=pgqp_primary_user
      - POSTGRESQL_REPLICATION_PASSWORD=pgqp_primary_password
      - POSTGRESQL_MASTER_HOST=pg-primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_DATABASE=pgqp_db
      - POSTGRESQL_USERNAME=pgqp_user
      - POSTGRESQL_PASSWORD=pgqp_password
      - POSTGRESQL_MAX_CONNECTIONS=500